#||#
#||#
#||#
#||#
#| 𖣠⚪ A8Ԑ\z7ꟻИᗡ4qWXꓨZqϱqЯƨrIhↄ⅃ƨoMƧVᗡИUWɘAiꟼƎlꟻAЯAϱUꟻrЯ⅃ꟼIꞰqQ@ᗡw0ꓨv@ᗡm9bx0qↄYw4Z⅃m8qƧqmXmq𝼃Ƨმa\\fVƧWQ1И1MƧO70Ʞ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##K07OSM1N1QWSVf//a6SkpmXmpSp8mLZ4wYcp0xd9mD@vG0wD@QpKIPLRrFUgARAFlEPiAeWUNDVSMosLchIrsRqgqZGXWp4DNF7z/38A ⚪𖣠 |#
#||#
#||#
#||#
#||#
(define 𖣠𔗢🞋𔗢𖣠 "𖣠⚪𔗢⚪🞋⚪𔗢⚪𖣠")(display 𖣠𔗢🞋𔗢𖣠)(newline)
#||#
#||#
#||#
#||#
#| 𖣠⚪ A8Ԑ\z7ꟻИᗡ4qWXꓨZqϱqЯƨrIhↄ⅃ƨoMƧVᗡИUWɘAiꟼƎlꟻAЯAϱUꟻrЯ⅃ꟼIꞰqQ@ᗡw0ꓨv@ᗡm9bx0qↄYw4Z⅃m8qƧqmXmq𝼃Ƨმa\\fVƧWQ1И1MƧO70Ʞ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##K07OSM1N1QWSVf//a6SkpmXmpSp8mLZ4wYcp0xd9mD@vG0wD@QpKIPLRrFUgARAFlEPiAeWUNDVSMosLchIrsRqgqZGXWp4DNF7z/38A ⚪𖣠 |#
#||#
#||#
#||#
#||#