--------
--------
--------
--------
---- 𖣠⚪ A8\\mfdTᗺꞰმVZƧᒐUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0O8\\nꟼ⅃ꞰzↄTq0M1Иlyy##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##yylN1M0pTczKLPn//8O0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUJSZV6KBTbfm//8A ⚪𖣠 ----
--------
--------
--------
--------
𖣠𔗢🞋𔗢𖣠="𖣠⚪𔗢⚪🞋⚪𔗢⚪𖣠"
print(𖣠𔗢🞋𔗢𖣠)
--------
--------
--------
--------
---- 𖣠⚪ A8\\mfdTᗺꞰმVZƧᒐUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0O8\\nꟼ⅃ꞰzↄTq0M1Иlyy##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##yylN1M0pTczKLPn//8O0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUJSZV6KBTbfm//8A ⚪𖣠 ----
--------
--------
--------
--------