////\\\\
////\\\\
////\\\\
////\\\\
//// 𖣠⚪ QA\\v2rꟼQᗺ8Iq0ƧƧtorzᗺl8ƧtϱwuxꓨI08ϱjᒐmWfxZ𝼃baϱƨTЯਟᗺᒐმAUUAƎᗺᗺa1ƨHhↄϱqƨИਟИAjb8მfY0\ꟻTm@ЯᗺirbYw7მlZმᒐꞰꞰoↄx𝼃ϱruzO0TzƎzИhQ0rzƨijXHTИoQꞰu\OjᒐᗺXVᒐ0ↄaOvMTOf9\\⅃xↄƧOԐƎ0o4yƧ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##Sy4o0E3OScxL//9fOTMvOac0JVXBJjO/uKQoNTHXjiszr0QhNzEzT0OzurgkxcoKKJ6Zl67wYdriBR@mTF/0Yf68bjAN5NsqgchHs1aBBEAUUA6JB5RTsgabkZxfWmJjg80IGxuwgtS8lBzrotSS0qI8BQPr2v//AQ ⚪𖣠 \\\\
////\\\\
////\\\\
////\\\\
////\\\\
 
#include <iostream>
int main(){std::string 𖣠𔗢🞋𔗢𖣠="𖣠⚪𔗢⚪🞋⚪𔗢⚪𖣠";std::cout<<𖣠𔗢🞋𔗢𖣠<<std::endl;return 0;}

////\\\\
////\\\\
////\\\\
////\\\\
//// 𖣠⚪ QA\\v2rꟼQᗺ8Iq0ƧƧtorzᗺl8ƧtϱwuxꓨI08ϱjᒐmWfxZ𝼃baϱƨTЯਟᗺᒐმAUUAƎᗺᗺa1ƨHhↄϱqƨИਟИAjb8მfY0\ꟻTm@ЯᗺirbYw7მlZმᒐꞰꞰoↄx𝼃ϱruzO0TzƎzИhQ0rzƨijXHTИoQꞰu\OjᒐᗺXVᒐ0ↄaOvMTOf9\\⅃xↄƧOԐƎ0o4yƧ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##Sy4o0E3OScxL//9fOTMvOac0JVXBJjO/uKQoNTHXjiszr0QhNzEzT0OzurgkxcoKKJ6Zl67wYdriBR@mTF/0Yf68bjAN5NsqgchHs1aBBEAUUA6JB5RTsgabkZxfWmJjg80IGxuwgtS8lBzrotSS0qI8BQPr2v//AQ ⚪𖣠 \\\\
////\\\\
////\\\\
////\\\\
////\\\\