////\\\\
////\\\\
////\\\\
////\\\\
//// 𖣠⚪ A8\\mfdTᗺꞰმVZƧᒐUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0Oↄ4ƎV7ᒐ\8f@xƨϽTꟼ7yꞰ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##Ky7PTCsx@f8/J7VE4cO0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUJSZV6KBTbfm//8A ⚪𖣠 \\\\
////\\\\
////\\\\
////\\\\
////\\\\
let 𖣠𔗢🞋𔗢𖣠="𖣠⚪𔗢⚪🞋⚪𔗢⚪𖣠"
print(𖣠𔗢🞋𔗢𖣠)
////\\\\
////\\\\
////\\\\
////\\\\
//// 𖣠⚪ A8\\mfdTᗺꞰმVZƧᒐUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0Oↄ4ƎV7ᒐ\8f@xƨϽTꟼ7yꞰ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##Ky7PTCsx@f8/J7VE4cO0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUJSZV6KBTbfm//8A ⚪𖣠 \\\\
////\\\\
////\\\\
////\\\\
////\\\\