#
#
#
#
# 𖣠⚪ AA\\\8ИᗺIrƧqꟻUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0O8\\zvqИqyꞰ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##KypNqvz//8O0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUFpSrIBN8///AA ⚪𖣠 #
#
#
#
#
𖣠𔗢🞋𔗢𖣠="𖣠⚪𔗢⚪🞋⚪𔗢⚪𖣠"
puts 𖣠𔗢🞋𔗢𖣠
#
#
#
#
# 𖣠⚪ AA\\\8ИᗺIrƧqꟻUVЯ8qo8ϱƎↄAꞰꞰAmϱAta2jЯꞰQVԐiƨꓨϱ1bɘ8ꟼMმ@mᒐT@ƨQx0O8\\zvqИqyꞰ##\ИUЯ.ⓄIT ⚪𔗢⚪🞋⚪𔗢⚪ TIⓄ.RUN/##KypNqvz//8O0xQs@TJm@6MP8ed1gGsi3VQKRj2atAgmAKKAcEg8op8RVUFpSrIBN8///AA ⚪𖣠 #
#
#
#
#